#!/usr/bin/env python3

from PIL import Image
import os
import sys
import zlib

buf_w, buf_h = map(int, os.getenv("size", "128x64").split("x"))


def load_image(filename):
    im = Image.open(filename)
    w, h = im.size
    buf = [0 for i in range(buf_w * buf_h // 8)]
    for y in range(min(h, buf_h)):
        for x in range(min(w, buf_w)):
            if im.getpixel((x, y)):
                buf[(y // 8) * buf_w + x] |= 1 << (y % 8)
    return buf


for i in range(1, len(sys.argv) - 2, 3):
    buf = (
        load_image(sys.argv[i])
        + load_image(sys.argv[i + 1])
        + load_image(sys.argv[i + 2])
    )
    c_buf = ",".join(map(str, buf))
    z_buf = zlib.compress(bytes(buf), 9)
    z_buf = z_buf[2:-4]
    out_buf = ",".join(map(str, z_buf))
    print(
        f'__attribute__((section(".text"))) unsigned char const frame{i:04d}[] = {{ {out_buf} }};'
    )

frames = list()
for i in range(1, len(sys.argv) - 2, 3):
    frames.append(f"(unsigned char*)frame{i:04d}")

prefix = '__attribute__((section(".text"))) unsigned char* const frames[] = {'
postfix = "};"

print(prefix + ", ".join(frames) + postfix)
