#!/bin/sh

set -e

touch .config

apps="countertest deflatetest donothing ledblink
	sysinfo"

make ext/libopencm3/lib/libopencm3_stm32f4.a

for app in $apps; do
	find src -name '*.o' -delete
	rm -f build/system.elf
	make arch=stm32f446re-nucleo app=$app build/system.elf
done
