#!/bin/sh

set -e

touch .config

apps="bme680-max44009-logger button-and-motion-logger
	donothing i2cdetect ledblink mpu9250_motionlog
	shell ssd1306test sysinfo timertest
	waittest wetterstation ws2812b_dmap ws2812b_uart"

for app in $apps; do
	make -B arch=arduino-nano app=$app build/system.elf
done
