#!/bin/sh

set -e

touch .config

apps="bme680-max44009-logger
	countertest deflatetest donothing i2cdetect ledblink
	nrf24l01test ssd1306test bad-apple-msp430fr-sharp96 sharp96test shell sysinfo timertest
	waittest"

for app in $apps; do
	make -B arch=msp430fr5994lp app=$app build/system.elf
done
