#!/bin/zsh
#
# Copyright 2020 Birte Kristina Friesel
#
# SPDX-License-Identifier: BSD-2-Clause


for i in {1..$#}; do
	if [[ $argv[$i] == *_agxx_* && -f $argv[$i] ]]; then
		sed -i 's/inline void \* operator new (unsigned int,/inline void * operator new(__int20 unsigned,/' $argv[$i]
	fi
done

exec /opt/msp430/ti/msp430-gcc-full-linux-5.1.2.0/bin/msp430-elf-g++ "$@"
